package com.aivle.agriculture.domain.calculate.dto;

public enum CropType {
    SWEET_POTATO,         // 고구마
    ONION,                // 양파
    WATERMELON,           // 수박
    SESAME,               // 참깨
    SOYBEAN,              // 콩
    RED_BEAN,             // 팥
    CABBAGE,              // 배추
    GARLIC,               // 마늘
    TEA,                  // 차
    AUTUMN_SQUASH,          // 단호박
    RICE,                 // 벼
    WHEAT,                // 밀
    BARLEY,               // 보리
    OAT,                  // 귀리
    CORN,                 // 옥수수
    POTATO,               // 감자
    CHESTNUT,             // 밤
    PEACH,                // 복숭아
    PLUM,                 // 자두
    MAESIL,               // 매실
    OMIJA,                // 오미자
    YUZU,                 // 유자
    WALNUT,               // 호두
    APRICOT,              // 살구
    CITRUS,               // 감귤(온주밀감류)
    JUJUBE,               // 대추
    GRAPE,                // 포도
    KIWI,                 // 참다래
    PEPPER,               // 고추
    BROCCOLI,             // 브로콜리
    CARROT,               // 당근
    RADISH,               // 무
    SPINACH,              // 시금치
    LETTUCE,              // 양상추
    BUCKWHEAT,            // 메밀
    STRAWBERRY,           // 딸기
    TOMATO,               // 토마토
    CUCUMBER,             // 오이
    KOREAN_MELON,               // 참외
    PUMPKIN,              // 호박
    PAPRIKA,              // 파프리카
    CHRYSANTHEMUM,        // 국화
    MELON,                // 멜론
    EGGPLANT,             // 가지
    GREEN_ONION,          // 대파
    SCALLION,             // 쪽파(실파)
    LILY,                 // 백합
    CARNATION,            // 카네이션
    WATER_PARSLEY,        // 미나리
    CROWN_DAISY,          // 쑥갓
    LOG_SHIITAKE,         // 원목재배 표고버섯
    OYSTER_MUSHROOM,      // 느타리버섯
    KING_OYSTER_MUSHROOM, // 새송이버섯
    BUTTON_MUSHROOM,      // 양송이버섯
    CHIVE,                // 부추
    GINSENG,              // 인삼
    MULBERRY,             // 오디
    DUREUP,                // 두릅
    BLUEBERRY,            // 블루베리
    BOKBUNJA,             // 복분자
    FIG                   // 무화과
}
